version: "3.4"

services:
  front:
    build: IMOMaritimeSingleWindow/Client
    ports:
      - "4201:4201"
    networks:
      - front
  back:
    build: IMOMaritimeSingleWindow/Server
    ports:
      - "5000:5000"
    networks:
      - front
      - back
  db:
    image: postgres:11-alpine
    networks:
      - back

networks:
  back:
  front: