version: "3.4"

services:
  front:
    build: IMOMaritimeSingleWindow/Client
    ports:
      - "4201:4201"
    networks:
      - front
  back:
    build: IMOMaritimeSingleWindow/Server
    ports:
      - "5000:5000"
    volumes:
      - ./conf/appsettings.json:/app/appsettings.json
    networks:
      - front
      - back
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: imo
      POSTGRES_DB: imomsw
      POSTGRES_PASSWORD: dik2dkDZXEt1GapxGwKVuVaZa5m5bS1oJWoF2stH
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    networks:
      - back

networks:
  back:
  front: